### ISSUE TITLE
Could you make some official anime plugins

### ISSUE THREAD

**Issue by CHJ85** [mrgsi/repository.allanime#1]
Hi there. There aren't any kodi plugins for Hidive and Funimation. There is one for Crunchyroll, but it's not working right.
If it's not too much to ask, do you think you could?
That'd be great. No pressure though.

**Comment by mrgsi** [comment]
I wish I could but I'm not an add-on coder. I have a couple add-ons I forked (very basic editing) but most of the stuff in my repos comes from other developers. I just repackage them into categories like All Anime for users seeking add-ons for that specific kind of content.

**Comment by CHJ85** [comment]
Okay. I see.
Thanks anyway.
